### PR TITLE
v2

### PR DESCRIPTION
**Pull request by Gummibeer**
blocked by https://github.com/spatie/enum/pull/56 & https://github.com/spatie/enum/pull/64

### CODE REVIEW

**Comment by Gummibeer** [comment]
Hey @brendt @AlexVanderbist , because of the new custom casts and also the array of enums support I think that we will have to drop the scopes. Otherwise they would get super complex.
What do you think? We don't have an array of attribute names and the corresponding enum anymore. We would have to parse all the possibilities in the regular $casts property.
Do you use/need these scopes?

**Comment by brendt** [comment]
@Gummibeer as you know I'm not using the package at the moment, so could you give an example with code why we'd need to drop the scopes?

**Comment by Gummibeer** [comment]
@brendt right now the scopes accept `int`, `string` and `Enumerable` - cast them to an `Enumerable` instance that's assigned to the attribute and use the optional attribute cast to decide if they use index or value for the query.
With the change to custom cast classes nearly nothing of this is possible.
The index or value could be done by an optional argument or different scopes.
For the casting of `int` and `string` we could try to use the `castAttribute()` method.
But all of this isn't this easy anymore. So I would like to check if the enum scopes are really used?
And if we keep them we have to add new ones for the enum collections. I would say that we will need scopes like _any_ and _all_ for the collections?

**Comment by brendt** [comment]
Would it be possible still to only support passing `Enumerable`s to the scopes? If we're properly casting values, it seems rather unlikely that the programmer will ever use anything but `Enumerable` implementations, so we could ditch the `string` and `int` support.

**Comment by Gummibeer** [comment]
By only allowing instances of Enumerable we will have to know if index or value.
Should we do this by different scopes or an optional argument? I prefer the different scopes solution.
Like `whereEnumIndex()` and `whereEnumValue()`.

**Comment by brendt** [comment]
Are we storing both the index and value of the enum in the database?

**Comment by Gummibeer** [comment]
No, only the one the user wants to store. By default we use the value but if there's an `int` cast for the attribute we store the index. That's already covered by the two different cast classes.

**Comment by SagarNaliyapara** [comment]
Expecting package will have immediate effect of [this](https://github.com/spatie/enum/pull/56), eagerly waiting to use updated version. @Gummibeer @brendt I'm just wonder how much time it will take after upgrade of https://github.com/spatie/enum?

**Comment by Gummibeer** [comment]
Hey,
it's right - I think first comment states that this PR is blocked by PHP base package.
Most time isn't required for coding but for decisions and real life testing. For the last part we are always happy to get community feedback who tried `dev-xyz` branch. Primary slim down major releases depend a lot on real life testing to be sure that we haven't removed any critical logic.

For example the scopes - do you use them? If so - how do you use them? Some real code snippets will make it easier for us to decide if we can drop them, slim down logic or have to keep them like is.

But I hope that we can finish this release ~1 week after base package release.

**Comment by kevindb** [comment]
I know spatie/enum released v3 just today. I'm excited to use patie/laravel-enum v2 when it's available. No pressure, just wanted to cheer you on and let you know laravel-enum has a following.
Cheers and thank you for the wonderful work!

**Comment by Gummibeer** [comment]
I'm sorry for the massive delay. Like sometimes something unexpected drops at work and a PR like this gets out of sight.
I'm working on this right now again.

**Comment by Gummibeer** [comment]
@SagarNaliyapara @AAllport @kevindb from package perspective it's done now. But I will add this version to some of my projects and try if everything works.
If you could spend some time testing it with your apps, or even only with your expectations/requirements in a fresh one and give feedback it would really help! 🙂

**Comment by Gummibeer** [comment]
Here's one super simple upgrade PATCH:
[upgrade_to_spatie_laravel-enum_v2.patch.txt](https://github.com/spatie/laravel-enum/files/5141790/upgrade_to_spatie_laravel-enum_v2.patch.txt)

**Comment by SagarNaliyapara** [comment]
Sure @Gummibeer I'll let you know how it goes

**Comment by Gummibeer** [comment]
Hey @SagarNaliyapara any news from your end? Were you able to test it?

**Comment by brendt** [comment]
Hey @Gummibeer , anything I can do to help this move forward?

**Comment by Gummibeer** [comment]
@brendt you could test it in your projects. Real world feedback is the only missing now. It's laravel 8 only because of the changed `castUsing()` signature.

**Comment by brendt** [comment]
@Gummibeer ok! We need to update our projects to L8 still, but we'll try to do this as soon as possible!

**Comment by ngunyimacharia** [comment]
Eagerly waiting for this as well 👍

**Comment by ngunyimacharia** [comment]
Meanwhile, for someone who wants a v3 approach with the v2 verson of the package, here is how I added value and label support:

```
  public function getValue(): string
  {
    return collect($this::values())->values()[$this->getIndex()];
  }

  public function getLabel(): string
  {
    return collect($this::labels())->values()[$this->getIndex()];
  }
```

**Comment by Gummibeer** [comment]
@ngunyimacharia are you able to test the current `v2.x-dev` in one of your projects?
We still need some real world feedback if everything works like expected or something is missing.

**Comment by ngunyimacharia** [comment]
> @ngunyimacharia are you able to test the current `v2.x-dev` in one of your projects?
> We still need some real world feedback if everything works like expected or something is missing.

@Gummibeer let me try it out.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-enum/releases/tag/2.0.0-rc.2

**Comment by Gummibeer** [comment]
Used the RC in one of our projects and everything works like a charm. This time a from-scratch implementation.
If I don't hear anything different I will release the official v2 end of the week.

**Comment by kevindb** [comment]
@Gummibeer I've been using `v2.x-dev` for a couple weeks now in a side project. It was working in Laravel 7, and is still working this week for my in Laravel 8. All of the base capabilities seem to be working perfectly! As far as I'm concerned, v2 is ready for prime time.  🎉

I ended up creating a wrapper class that my Enums inherit from, so that I could provide some helper functions. Please let me know if there is a better way; I'm happy to be told I'm making things hard on myself.
https://gist.github.com/kevindb/0373fdd844a201ac9ce901d2ec3b0b3a

`getRandom()` is useful for factories and tests.
`getValues()`, `getNames()`, `getLabels()`, and `toArrayForBackpack()` are useful for populating select dropdowns, e.g. for Backpack:
`CRUD::field('purpose')->type('select_from_array')->options(DealPurposeEnum::toArrayForBackpack());`

**Comment by Gummibeer** [comment]
@kevindb is there a reason why you have `getNames()` and `getValues()` doing the same? And your `toArrayForBackpack()` does also the same as the default `toArray()`.
https://github.com/spatie/enum/blob/3753a492bc97cf700f230e3f0880bc7104433994/src/Enum.php#L27-L36

You should also use `toArray()` with `array_keys()` or `array_values()` to get all values/labels. The current `values()` & `labels()` methods are optional and only for mapping.

@brendt that's also what bothered me the most. Could we change the current `values()` & `labels()` methods to `valueMap()` and `labelMap()` and add `values()` and `labels()` as real method returning all values/labels?
So simply a wrapper for `array_keys(MyEnum::toArray())`. 

The random is a good idea, had a similar in the last project but decided for `$faker->randomElement(array_keys(MyEnum::toArray()))` which is a bit bulky - it would get better with the above suggestion.
But How about a Faker plugin that you can do `$faker->randomEnumValue(MyEnum::class)`? I don't want this on my regular app enum class as it's only for testing - that's why I've dropped the idea. But a Faker plugin would be perfect for this - I think!?

**Comment by Gummibeer** [comment]
@kevindb here you go https://github.com/spatie/laravel-enum/pull/44/commits/52031dff67abbd53e0f8321364f9df8ad9259580 😉 
https://github.com/spatie/laravel-enum/releases/tag/2.0.0-rc.3 🚀

**Comment by kevindb** [comment]
> @kevindb here you go [026e04d](https://github.com/spatie/laravel-enum/commit/026e04d9ea8c1fa85db4c8dbf88f44aad8cc75ae) 😉

Ooh! Thank you! I'll try out the new Faker provider this week.

>The current values() & labels() methods are optional and only for mapping.

I do have values and labels defined for all my Enums. Values are necessary because I want to save integers to the database. Labels are necessary to populate the selects.

> is there a reason why you have getNames() and getValues() doing the same?

`getValues()` is using array_**values**, whereas `getNames()` is using array_**keys**. It's subtle, I had to read my code twice to see the difference.

> And your toArrayForBackpack() does also the same as the default toArray().

I wrote this wrapper on Aug 2. At the time, the Enum Validator only accepted Enum names, not the integer values. So toArrayForBackpack generates an array of names::labels, instead of toArray's values::labels.
I see now that the Validator has been updated to accept values too. I'll try toArray() now to see if it works.

**Comment by Gummibeer** [comment]
I see so you are rebuilding the base enum v2 behavior with 3 different value types of an enum.
So there isn't really anymore we would have to move in this package - as psalm is now also added and passes and we have some real world feedback I think we are good to release tomorrow. 🎉🚀

**Comment by brendt** [comment]
> I think we are good to release tomorrow

👍

**Comment by AlexVanderbist** [comment]
Diff view in the "files changed" tab was too messy so went through the entire package again. Looks good to me! I'll probably start using this in a hobby project in a couple of weeks 👍

**Review by AlexVanderbist — APPROVED** [review]

**Comment by Gummibeer** [comment]
@AlexVanderbist yeah, a lot has changed. Most of my commit messages should also be readable and meaningful.

Thanks for the approvals. If no one of you releases it today I will do this afternoon/night or tomorrow. 🚀

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-enum/releases/tag/2.0.0

**Pull request merged**
