### PR TITLE
Support Laravel 11

### PR DESCRIPTION
**Pull request by justinaskav**
Updated some package versions to support Laravel 11, tests are passing. Maybe some more excludes should be added in run-tests.yml.

### CODE REVIEW

**Comment by scajal** [comment]
Any news on this?

**Comment by rickmills** [comment]
+1

For what its worth I'm running the forked branch temporarily until this merges and it's working correctly on a project that has been migrated to Laravel 11.

**Comment by keatliang2005** [comment]
side note, the native L11 now with `make:enum` artisan command, it's a conflict with the package command

**Comment by gainlinejono** [comment]
+1

**Comment by justinaskav** [comment]
> side note, the native L11 now with `make:enum` artisan command, it's a conflict with the package command

Don't really know if Spatie has any system for their commands, but I made an update so it wouldn't conflict with L11.

@rubenvanassche since the last Laravel version update was released by you, maybe you could look into this PR?

**Comment by gainlinejono** [comment]
Hi guys, really appreciate the work put into the Spatie lifecycle of packages.

Unfortunately this package is the only blocker for an upgrade to Laravel 11.

Is it possible to get some form of timeline for an update to this package if possible?

Thanks also to @justinaskav for submitting a PR!

**Comment by vrusua** [comment]
+1

**Comment by rubenvanassche** [comment]
Thanks!

**Pull request merged**
