### PR TITLE
Route binding

### PR DESCRIPTION
**Pull request by Gummibeer**
follow up to #62 

the drop of `TransformEnums` middleware isn't breaking in this case as the middleware is/was unusable the current way - described by @binotaliu in #62 .
@brendt do you think the same? Or should I keep it in the package and just flag it as `@deprecated` - just in case?

### CODE REVIEW

**Comment by binotaliu** [comment]
I think I forget to mention `InvalidEnumValueException` in the documentation. It need to be added to `app/Exceptions/Handler.php` in order to show 404 page.

**Comment by Gummibeer** [comment]
Hey @binotaliu , you already prepared this exception to handle this on its own.
It extends the `\Symfony\Component\HttpKernel\Exception\NotFoundHttpException` and all Symfony HTTP exceptions are properly handled by the default exception handler.

**Comment by brendt** [comment]
> do you think the same?

@Gummibeer I think the same :) if it was unusable anyway there's no need to keep it 👍

**Comment by Gummibeer** [comment]
Okay, I will add a note/warning in the changelog so if someone really used it will find quickly why it's now exploding.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-enum/releases/tag/2.4.0

**Pull request merged**
