### PR TITLE
Add PHP 8.2 Support

### PR DESCRIPTION
**Pull request by patinthehat**
# Summary

This PR adds PHP 8.2 to the tests workflow.

_id:php82-support/v1_

### CODE REVIEW

**Comment by patinthehat** [comment]
ping @freekmurze

**Comment by patinthehat** [comment]
Open to ideas on this - not sure why tests are failing for P8 + L9.

**Comment by patinthehat** [comment]
@freekmurze Should be good to re-run tests :+1:

**Comment by freekmurze** [comment]
Almost! Still a couple of failing tests.

**Comment by patinthehat** [comment]
@freekmurze Hmmm. I went ahead and removed the problem line, all tests are passing on my local now.

**Comment by freekmurze** [comment]
Looks good now, thanks!

**Pull request merged**
