### PR TITLE
request transform

### PR DESCRIPTION
**Pull request by Gummibeer**
This is my first idea how to implement a request transformer via FormRequest, Request macro and Middleware.
It's untested but should give a good idea of how it's done and could be used.

* `FormRequest` auto transforms during resolvance - after validation
* `Middleware` have to used via `new TransformEnums([...])` but can transform everything, including route params
* `Request::transformEnums()` is the base implementation which is used by all others

Some code and ideas are from https://github.com/konsulting/laravel-transformer

### CODE REVIEW

**Comment by Gummibeer** [comment]
@brendt after some refactorings and adding all the missing unittests the provided examples aren't complete now.
I've added the option to transform enums related to query/request/route separated to don't get conflicts and assign them back to the right bag instead of just throwing them into the default input wrapper.

**Comment by Gummibeer** [comment]
**ToDo:** Check if https://laravel.com/docs/5.8/validation#after-validation-hook could be used.

**Comment by Gummibeer** [comment]
@brendt I would need this in a current project. Could you review this PR again? :)

**Comment by Gummibeer** [comment]
I've increased the minimum Laravel version to `v5.8.33` because of the usage of `passedValidation()`.
https://blog.laravel.com/laravel-v5-8-33-released
https://github.com/laravel/framework/pull/29549

**Comment by Gummibeer** [comment]
@brendt all errors should be fixed now. :)
Would be great if you could review this PR. After this PR I will open a new one with improved readme and docs.

**Comment by brendt** [comment]
@Gummibeer I'd add the docs in the same PR, no?

**Comment by brendt** [comment]
Nvm, I just saw #30 :)

**Comment by Gummibeer** [comment]
@brendt @AlexVanderbist I will add a new v1.4.0 release somewhen this week containing these two PRs.
After this I will start the Laravel 7 custom cast PR that will drop Laravel 5/6 support - #31

**Comment by brendt** [comment]
Great!

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-enum/releases/tag/1.4.0

**Pull request merged**
