### PR TITLE
Added Macroable

### PR DESCRIPTION
**Pull request by thecaliskan**

### CODE REVIEW

**Comment by Gummibeer** [comment]
Hey,

why should/would you macro an enum? Enums are finite lists of values and should be nothing more. The PHP8.1 spec allows methods, which we also do, to retrieve related values to the current enum value - for example the color per status.
But this can be done within the enum class itself and doesn't require an enum.

Right now adding macros to an enum is an anti-pattern for me, so if you don't have a really convincing use-case for it I will reject that PR.

**Comment by thecaliskan** [comment]
Hi;

Php 8.1 release date so long ?? November 2021

Output format change like;
```php 
Enum::macro('toArrayWithKeys', function ($name = 'name', $id = 'id'){
    return collect(self::toArray())->map(function ($item, $key) use ($name,$id) {
        return [
            $id => $key,
            $name => $item,
        ];
    })->toArray();
});
```

**Comment by thecaliskan** [comment]
Reasonable request to me

**Comment by Gummibeer** [comment]
You can add this method to your base enum class and use it. No need for a macro as you own the code and change it however you want/need to.

**Comment by thecaliskan** [comment]
Macro's logic is to use it when needed, not just in this case.

**Comment by Gummibeer** [comment]
The absolute only case macros would be the one way to solve a problem is a `final` enum in a package or similar you can't control. And even in that case a formatted class or similar could do the job as well.
Macros on the enum are just bad practice and therefore I won't merge them in.

**Pull request closed without merging**
