### PR TITLE
run GH action failure Slack notification only on master builds

### PR DESCRIPTION
**Pull request by Gummibeer**

### CODE REVIEW

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-enum/pull/28/checks?sha=fb9ee8c977495c3798d99f0b1ce21a96da5d7646
@freekmurze the slack isn't triggered even if the build fails.

**Comment by freekmurze** [comment]
I'm thinking the current workflow does work. I've just let the actual tests fail and I got a notification: https://github.com/spatie/laravel-enum/runs/378021998

**Comment by freekmurze** [comment]
Are you sure the `&& github.ref == 'refs/heads/master'` is correct?

**Comment by Gummibeer** [comment]
The problem this solves is to prevent fail slack messages for every branch/PR and only notify failing master builds.
Like discussed in #27 

And yes, it's a git standard. Nothing GitHub specific.
https://git-scm.com/docs/git-show-ref#_examples

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
