### PR TITLE
Adds an example Enum class to the readme

### LINKED ISSUE #53: Nullable not working as expected
The `nullable` cast gets validated as being an actual string value when using:

```php
protected $casts = [
   'status' => SomeStatusEnum::class.':nullable'
];
```

Exception: (`spatie\Enum` class) [expects a $value, "nullable" gets passed]
`There's no value "nullable" defined for enum SomeStatusEnum, consider adding it in the docblock definition.`

Removing the `:nullable` cast, also returns the exception that it's not passing (the expected number of) parameters
( see also spatie/enum#70 )

When I change it to eg. SomeStatusEnum::class.`:collection,nullable` the above occurs with constructor $value `"collection"`

### PR DESCRIPTION
**Pull request by xewl**
As it wasn't very/directly apparent from the readme to extend from the actual Enum class made for Laravel [imho];
this PR adds an example Enum class based on the existing `StatusEnum` example being used, and a link to the documentation of spatie/enum.

@Gummibeer - I'm not that familiar with putting this all in the correct wording... _guide me senpai_ 😁 

closes #53

### CODE REVIEW

**Comment by brendt** [comment]
The first thing the README does is link to `spatie/enum`. I'd expect the users of this package to know the base package it's built upon. 

On the other hand, there's no harm in adding this to the README I suppose, if it's unclear for some.

**Comment by Gummibeer** [comment]
There's a slight difference - the different base classes.
That's what this PR is primary about.

**Comment by xewl** [comment]
> The first thing the README does is link to `spatie/enum`. I'd expect the users of this package to know the base package it's built upon.

> There's a slight difference - the different base classes.

Well, that answered itself.
But yes, the main aim for this PR is to make clear that there's a difference.
I was migrating code to v2, while still using the original use statement.
Because I didn't make a new Enum class, I didn't really notice the difference from either:
- the readme (even though, it's stated in the first sentence
- any of the example code below that.

The documentation for  `spatie/enum` of course just uses the initial class too.

The example is to give readers a glance of which actual use statement to use,
and the notice below it does repeat the link to the actual documentation.
The latter, I'm pretty sure, can't hurt to note though..

I'm willing to change this to whatever you guys think is best, this is just my take.

**Comment by Gummibeer** [comment]
So, now I have some time to handle this.
I've added a simple docs page to the base package about the Laravel wrapper: https://github.com/spatie/enum/commit/7e2156adef41c7ae9fcd60ad4de26eeec45c9518

On top I will merge this and slim it a bit down and highlight the important line in favor of what Brent said that most of this is the same as in the base package and you should know how the base package works before implementing the advanced laravel features.

**Pull request merged**
