### PR TITLE
Add Laravel 6 support

### PR DESCRIPTION
**Pull request by supertassu**
This PR allow installing the package to Laravel 6 applications.

### CODE REVIEW

**Comment by Gummibeer** [comment]
@brendt because there's no stable release until now: would you mind to only support Laravel 6? Or should we stick with all compatible versions? In this case we could add >=5.6?

**Comment by brendt** [comment]
Let's only support the latest two: 5.8 and 6.0

**Comment by Gummibeer** [comment]
@supertassu thanks! Will release a new beta and discuss with @brendt how we will proceed.

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-enum/releases/tag/1.0.0-beta.3
released

**Pull request merged**
