### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by maldechavda**
This is my first attempt for GitHub action. Let me know if missing anything.

Thanks!

### CODE REVIEW

**Comment by freekmurze** [comment]
Thanks!

**Comment by Gummibeer** [comment]
@freekmurze do you want the slack notifications? I bet this will "kill" your slack if you do it for all your OS packages and no one will care about the important notifications anymore!?
I mean all these OS package PRs aren't this urgent that you need a slack message if a build fails!?

**Comment by freekmurze** [comment]
Yeah, good point. Maybe I should figure out on how to only get a notification when the tests on the master branch fails. Feel free to PR that if you already know how to do this :-)

**Comment by Gummibeer** [comment]
https://github.community/t5/GitHub-Actions/GitHub-Actions-branch-conditional/td-p/29794
```
if: github.ref == 'refs/heads/master'
```

would need to check how to combine the two conditions - if it's a simple `&&`?

**Pull request merged**
